/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author raray
 */
public class Books extends javax.swing.JPanel {
    connection con;
    /**
     * Creates new form Books
     */
    public Books() {
        initComponents();
        con = new connection();
        loadBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldcari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledatabuku = new javax.swing.JTable();
        jLabelcari = new javax.swing.JLabel();
        delBtn = new javax.swing.JLabel();
        addBtn = new javax.swing.JLabel();
        editBtn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(249, 248, 248));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jTextFieldcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcariActionPerformed(evt);
            }
        });

        jTabledatabuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabledatabuku);

        jLabelcari.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelcari.setForeground(new java.awt.Color(204, 204, 204));
        jLabelcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/search.png"))); // NOI18N
        jLabelcari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelcariMouseClicked(evt);
            }
        });

        delBtn.setBackground(new java.awt.Color(255, 204, 153));
        delBtn.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        delBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/del.png"))); // NOI18N
        delBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delBtnMouseClicked(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(255, 204, 153));
        addBtn.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/add.png"))); // NOI18N
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 204, 153));
        editBtn.setFont(new java.awt.Font("Corbel", 0, 48)); // NOI18N
        editBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/edit--.png"))); // NOI18N
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Tambah");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Ubah");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Hapus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 647, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelcari)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(29, 29, 29)
                        .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldcari)
                            .addComponent(jLabelcari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelcariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelcariMouseClicked
        searchBook();
    }//GEN-LAST:event_jLabelcariMouseClicked

    private void jTextFieldcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcariActionPerformed
        searchBook();
    }//GEN-LAST:event_jTextFieldcariActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        new tambahbuku().setVisible(true);
    }//GEN-LAST:event_addBtnMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        loadBooks();
        
        if (!jTextFieldcari.getText().isEmpty()) {
            jTextFieldcari.setText("");
        }
    }//GEN-LAST:event_formMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        int baris = jTabledatabuku.getSelectedRow();
        if(baris!=-1){
            String id = jTabledatabuku.getValueAt(baris, 0).toString();
            idbuku.setId(id.substring(id.lastIndexOf("-") + 1));
//            JOptionPane.showMessageDialog(null, idbuku.getId());
            new editbuku().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_editBtnMouseClicked

    private void delBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delBtnMouseClicked
        int baris = jTabledatabuku.getSelectedRow();
        if (baris!=-1) {
            String id = jTabledatabuku.getValueAt(baris, 0).toString();
            idbuku.setId(id.substring(id.lastIndexOf("-") + 1));
            String input = "DELETE FROM book where id=" + idbuku.getId() + "";

            try {
                Statement st = con.con.createStatement();
                st.executeUpdate(input);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "Data Gagal dihapus","Gaagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delBtnMouseClicked

    private void searchBook() {
        String cari;
        cari = jTextFieldcari.getText();
        Object header[]={"No", "Judul", "Pengarang", "Penerbit", "Tahun", "Kategori", "Status", " "};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTabledatabuku.setModel(data);
        String buku = "select * from book INNER JOIN `status` ON book.status_id=status.id INNER JOIN `category` ON book.category_id=category.id where book.title like '%"+cari+"%' ORDER by book.id";
        
        try{Statement st = con.con.createStatement();
            ResultSet rs = st.executeQuery(buku);
            while(rs.next()){
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(3);
                String kolom3 = rs.getString(4);
                String kolom4 = rs.getString(5);
                String kolom5 = rs.getString(6);
                String kolom6 = rs.getString(12);
                String kolom7 = rs.getString(10);
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7};
                data.addRow(kolom);}
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
        }
    }
    
    public void loadBooks() {
        Object header[]={"Kode Buku", "Judul", "Pengarang", "Penerbit", "Tahun", "Kategori", "Status"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTabledatabuku.setModel(data);
        String buku = "SELECT * FROM book JOIN status ON book.status_id=status.id JOIN category ON book.category_id=category.id order by book.id";
        
        try {
            Statement st = con.con.createStatement();
            ResultSet rs = st.executeQuery(buku);
            
            while(rs.next()){
                String kolom1 = rs.getString(2);
                String kolom2 = rs.getString(3);
                String kolom3 = rs.getString(4);
                String kolom4 = rs.getString(5);
                String kolom5 = rs.getString(6);
                String kolom6 = rs.getString(12);
                String kolom7 = rs.getString(10);
                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7};
                data.addRow(kolom);
            }    
        }
        catch(Exception e) {
                JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
            }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel delBtn;
    private javax.swing.JLabel editBtn;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelcari;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledatabuku;
    private javax.swing.JTextField jTextFieldcari;
    // End of variables declaration//GEN-END:variables
}
