/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

/**
 *
 * @author fandi
 */
public class datapinjam extends javax.swing.JFrame {

    /**
     * Creates new form datapinjam
     */
    public datapinjam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabledatapinjam = new javax.swing.JTable();
        jLabelcari = new javax.swing.JLabel();
        jTextFieldcari = new javax.swing.JTextField();
        jPanelwelcome = new javax.swing.JPanel();
        jLabelmenu = new javax.swing.JLabel();
        jLabelbuku1 = new javax.swing.JLabel();
        jLabelkategori1 = new javax.swing.JLabel();
        jLabelpinjam1 = new javax.swing.JLabel();
        jLabeltambah1 = new javax.swing.JLabel();
        jLabelfavorit1 = new javax.swing.JLabel();
        jLabelabout1 = new javax.swing.JLabel();
        jPanelmenuutama = new javax.swing.JPanel();
        jLabeldatapinjam = new javax.swing.JLabel();
        jLabelclose = new javax.swing.JLabel();
        jLabelminimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(645, 425));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jTabledatapinjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabledatapinjam);

        jLabelcari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/icons8_Search_40px.png"))); // NOI18N
        jLabelcari.setText("Cari");

        jTextFieldcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelcari, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcari)
                    .addComponent(jTextFieldcari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelmenu.setText("Menu Utama");

        jLabelbuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/book1.png"))); // NOI18N
        jLabelbuku1.setText("Data Buku");

        jLabelkategori1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/kategori1.png"))); // NOI18N
        jLabelkategori1.setText("Kategori Buku");

        jLabelpinjam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/stack book1.png"))); // NOI18N
        jLabelpinjam1.setText("Data Pinjam");

        jLabeltambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/tambah1.png"))); // NOI18N
        jLabeltambah1.setText("Peminjaman / Pengembalian Buku");

        jLabelfavorit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/favorit1.png"))); // NOI18N
        jLabelfavorit1.setText("Buku Favorit");

        jLabelabout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/about1.png"))); // NOI18N
        jLabelabout1.setText("About");

        javax.swing.GroupLayout jPanelwelcomeLayout = new javax.swing.GroupLayout(jPanelwelcome);
        jPanelwelcome.setLayout(jPanelwelcomeLayout);
        jPanelwelcomeLayout.setHorizontalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeltambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGroup(jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelkategori1)
                    .addComponent(jLabelpinjam1)
                    .addComponent(jLabelfavorit1)
                    .addComponent(jLabelabout1)
                    .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelmenu))
                    .addComponent(jLabelbuku1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelwelcomeLayout.setVerticalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelmenu)
                .addGap(27, 27, 27)
                .addComponent(jLabelbuku1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelkategori1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpinjam1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltambah1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelfavorit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelabout1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanelmenuutama.setBackground(new java.awt.Color(34, 47, 62));

        jLabeldatapinjam.setForeground(new java.awt.Color(255, 255, 255));
        jLabeldatapinjam.setText("Data Pinjam");

        jLabelclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/close.png"))); // NOI18N

        jLabelminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/minimize.png"))); // NOI18N

        javax.swing.GroupLayout jPanelmenuutamaLayout = new javax.swing.GroupLayout(jPanelmenuutama);
        jPanelmenuutama.setLayout(jPanelmenuutamaLayout);
        jPanelmenuutamaLayout.setHorizontalGroup(
            jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuutamaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelminimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose))
            .addGroup(jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelmenuutamaLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabeldatapinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(590, Short.MAX_VALUE)))
        );
        jPanelmenuutamaLayout.setVerticalGroup(
            jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelclose)
            .addComponent(jLabelminimize)
            .addGroup(jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelmenuutamaLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabeldatapinjam)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanelmenuutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelmenuutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datapinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datapinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datapinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datapinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datapinjam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelabout1;
    private javax.swing.JLabel jLabelbuku1;
    private javax.swing.JLabel jLabelcari;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabeldatapinjam;
    private javax.swing.JLabel jLabelfavorit1;
    private javax.swing.JLabel jLabelkategori1;
    private javax.swing.JLabel jLabelmenu;
    private javax.swing.JLabel jLabelminimize;
    private javax.swing.JLabel jLabelpinjam1;
    private javax.swing.JLabel jLabeltambah1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelmenuutama;
    private javax.swing.JPanel jPanelwelcome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabledatapinjam;
    private javax.swing.JTextField jTextFieldcari;
    // End of variables declaration//GEN-END:variables
}
