/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

/**
 *
 * @author fandi
 */
public class kategoribuku extends javax.swing.JFrame {

    /**
     * Creates new form kategoribuku
     */
    public kategoribuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabelkomik = new javax.swing.JLabel();
        jLabelnovel = new javax.swing.JLabel();
        jLabelumum = new javax.swing.JLabel();
        jLabelbahasa = new javax.swing.JLabel();
        jLabelipa = new javax.swing.JLabel();
        jLabelips = new javax.swing.JLabel();
        jLabelteknologi = new javax.swing.JLabel();
        jLabelmatematika = new javax.swing.JLabel();
        jLabelseni = new javax.swing.JLabel();
        jLabelbahasaicon = new javax.swing.JLabel();
        jLabelagamaicon = new javax.swing.JLabel();
        jLabelipaicon = new javax.swing.JLabel();
        jLabelipsicon = new javax.swing.JLabel();
        jLabelteknologiicon = new javax.swing.JLabel();
        jLabelseniicon = new javax.swing.JLabel();
        jLabelkomikicon = new javax.swing.JLabel();
        jLabelumumicon = new javax.swing.JLabel();
        jLabelnovelicon = new javax.swing.JLabel();
        jLabelmatematikaicon = new javax.swing.JLabel();
        jLabelagama = new javax.swing.JLabel();
        jPanelwelcome = new javax.swing.JPanel();
        jLabelmenuutama = new javax.swing.JLabel();
        jLabelbuku1 = new javax.swing.JLabel();
        jLabelkategori1 = new javax.swing.JLabel();
        jLabelpinjam1 = new javax.swing.JLabel();
        jLabeltambah1 = new javax.swing.JLabel();
        jLabelfavorit1 = new javax.swing.JLabel();
        jLabelabout1 = new javax.swing.JLabel();
        jPanelmenuutama = new javax.swing.JPanel();
        jLabelkategori = new javax.swing.JLabel();
        jLabelclose = new javax.swing.JLabel();
        jLabelminimize = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(645, 425));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabelkomik.setText("Komik");

        jLabelnovel.setText("Novel");

        jLabelumum.setText("Umum");

        jLabelbahasa.setText("Bahasa");

        jLabelipa.setText("IPA");

        jLabelips.setText("IPS");

        jLabelteknologi.setText("Teknologi");

        jLabelmatematika.setText("Matematika");

        jLabelseni.setText("Seni dan Rekreasi");

        jLabelbahasaicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/bahasa.png"))); // NOI18N

        jLabelagamaicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/agama.png"))); // NOI18N

        jLabelipaicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/ipa.png"))); // NOI18N

        jLabelipsicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/ips.png"))); // NOI18N

        jLabelteknologiicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/teknologi.png"))); // NOI18N

        jLabelseniicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/seni.png"))); // NOI18N

        jLabelkomikicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/komik.png"))); // NOI18N

        jLabelumumicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/umum.png"))); // NOI18N

        jLabelnovelicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/novel.png"))); // NOI18N

        jLabelmatematikaicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/mathe.png"))); // NOI18N

        jLabelagama.setText("agama");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabelumum)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelips)
                                .addGap(72, 72, 72)
                                .addComponent(jLabelipa)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabelmatematikaicon)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelseniicon)
                            .addComponent(jLabelagama))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelipsicon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelipaicon)
                        .addGap(46, 46, 46)
                        .addComponent(jLabelagamaicon)))
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabelteknologiicon)
                        .addComponent(jLabelteknologi)
                        .addComponent(jLabelumumicon))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelnovel))
                            .addComponent(jLabelnovelicon))))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelkomikicon)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelbahasa)
                        .addComponent(jLabelbahasaicon))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabelkomik)))
                .addGap(37, 37, 37)
                .addComponent(jLabelmatematika)
                .addGap(28, 28, 28)
                .addComponent(jLabelseni)
                .addGap(91, 91, 91))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelipsicon)
                    .addComponent(jLabelipaicon)
                    .addComponent(jLabelumumicon)
                    .addComponent(jLabelagamaicon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelumum)
                        .addComponent(jLabelipa)
                        .addComponent(jLabelagama))
                    .addComponent(jLabelips))
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelbahasaicon)
                            .addComponent(jLabelseniicon)
                            .addComponent(jLabelmatematikaicon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelteknologi)
                                .addComponent(jLabelmatematika)
                                .addComponent(jLabelseni))
                            .addComponent(jLabelbahasa)))
                    .addComponent(jLabelteknologiicon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelkomikicon)
                    .addComponent(jLabelnovelicon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelkomik)
                    .addComponent(jLabelnovel))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabelmenuutama.setText("Menu Utama");

        jLabelbuku1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/book1.png"))); // NOI18N
        jLabelbuku1.setText("Data Buku");

        jLabelkategori1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/kategori1.png"))); // NOI18N
        jLabelkategori1.setText("Kategori Buku");

        jLabelpinjam1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/stack book1.png"))); // NOI18N
        jLabelpinjam1.setText("Data Pinjam");

        jLabeltambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/tambah1.png"))); // NOI18N
        jLabeltambah1.setText("Peminjaman / Pengembalian Buku");

        jLabelfavorit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/favorit1.png"))); // NOI18N
        jLabelfavorit1.setText("Buku Favorit");

        jLabelabout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/about1.png"))); // NOI18N
        jLabelabout1.setText("About");

        javax.swing.GroupLayout jPanelwelcomeLayout = new javax.swing.GroupLayout(jPanelwelcome);
        jPanelwelcome.setLayout(jPanelwelcomeLayout);
        jPanelwelcomeLayout.setHorizontalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabeltambah1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGroup(jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelkategori1)
                    .addComponent(jLabelpinjam1)
                    .addComponent(jLabelfavorit1)
                    .addComponent(jLabelabout1)
                    .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabelmenuutama))
                    .addComponent(jLabelbuku1))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelwelcomeLayout.setVerticalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelmenuutama)
                .addGap(27, 27, 27)
                .addComponent(jLabelbuku1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelkategori1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelpinjam1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabeltambah1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelfavorit1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelabout1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanelmenuutama.setBackground(new java.awt.Color(34, 47, 62));

        jLabelkategori.setForeground(new java.awt.Color(255, 255, 255));
        jLabelkategori.setText("kategori buku");

        jLabelclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/close.png"))); // NOI18N

        jLabelminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubes/pic/minimize.png"))); // NOI18N

        javax.swing.GroupLayout jPanelmenuutamaLayout = new javax.swing.GroupLayout(jPanelmenuutama);
        jPanelmenuutama.setLayout(jPanelmenuutamaLayout);
        jPanelmenuutamaLayout.setHorizontalGroup(
            jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelmenuutamaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelminimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelclose))
            .addGroup(jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelmenuutamaLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabelkategori, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        jPanelmenuutamaLayout.setVerticalGroup(
            jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelclose)
            .addComponent(jLabelminimize)
            .addGroup(jPanelmenuutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelmenuutamaLayout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jLabelkategori)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelmenuutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelmenuutama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategoribuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategoribuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategoribuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategoribuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kategoribuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelabout1;
    private javax.swing.JLabel jLabelagama;
    private javax.swing.JLabel jLabelagamaicon;
    private javax.swing.JLabel jLabelbahasa;
    private javax.swing.JLabel jLabelbahasaicon;
    private javax.swing.JLabel jLabelbuku1;
    private javax.swing.JLabel jLabelclose;
    private javax.swing.JLabel jLabelfavorit1;
    private javax.swing.JLabel jLabelipa;
    private javax.swing.JLabel jLabelipaicon;
    private javax.swing.JLabel jLabelips;
    private javax.swing.JLabel jLabelipsicon;
    private javax.swing.JLabel jLabelkategori;
    private javax.swing.JLabel jLabelkategori1;
    private javax.swing.JLabel jLabelkomik;
    private javax.swing.JLabel jLabelkomikicon;
    private javax.swing.JLabel jLabelmatematika;
    private javax.swing.JLabel jLabelmatematikaicon;
    private javax.swing.JLabel jLabelmenuutama;
    private javax.swing.JLabel jLabelminimize;
    private javax.swing.JLabel jLabelnovel;
    private javax.swing.JLabel jLabelnovelicon;
    private javax.swing.JLabel jLabelpinjam1;
    private javax.swing.JLabel jLabelseni;
    private javax.swing.JLabel jLabelseniicon;
    private javax.swing.JLabel jLabeltambah1;
    private javax.swing.JLabel jLabelteknologi;
    private javax.swing.JLabel jLabelteknologiicon;
    private javax.swing.JLabel jLabelumum;
    private javax.swing.JLabel jLabelumumicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelmenuutama;
    private javax.swing.JPanel jPanelwelcome;
    // End of variables declaration//GEN-END:variables
}
